name: CI
on:
  push:
  pull_request:
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    services:
      backend:
        image: ghcr.io/graalvm/jdk-community:21
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: 'maven'
      - name: Make Maven Wrapper executable
        run: chmod +x ./mvnw
        working-directory: backend
      - name: Build and run unit tests
        working-directory: backend
        run: ./mvnw -B -q -DskipITs=true test
      - name: Run BDD tests
          # Wait for backend to be available
          for i in {1..10}; do
            if curl --output /dev/null --silent --head --fail http://localhost:9090/actuator/health; then
              echo "Backend is up!"; break;
            else
              echo "Waiting for backend..."; sleep 5;
            fi
          done
        working-directory: backend
        run: ./mvnw -B -q -Dtest=com.example.backend.bdd.CucumberTest test
      - name: Run API tests (REST Assured)
        working-directory: backend
          CHROME_USER_DATA_DIR: /tmp/chrome-user-data-$GITHUB_RUN_ID
        run: |
          nohup ./mvnw -q spring-boot:run &
          sleep 20
          ./mvnw -B -q -Dtest=com.example.backend.api.TaskApiTests -Dapi.base=http://localhost:9090 test
      - name: Run Selenium UI tests (optional, headless)
        env:
          frontend_url: http://localhost:5173
        working-directory: backend
        run: |
          sudo apt-get update && sudo apt-get install -y xvfb
          Xvfb :99 &
          export DISPLAY=:99
          ./mvnw -B -q -Dtest=com.example.backend.ui.SeleniumTests -Dfrontend.url=$frontend_url test || echo "Skipping if frontend not running"